version: "3.9"

services:
  db:
    image: postgres:15
    container_name: alphasys-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alphasys
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alphasys-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alphasys
      - JWT_SECRET=supersecretkey
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alphasys-frontend
    command: streamlit run frontend/app.py --server.port 8501 --server.enableCORS false
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app

volumes:
  db_data: