"""add description to leave types

Revision ID: 20251111_add_description_to_leave_types
Revises: 20251111_104500_add_position_and_employment_status_tables
Create Date: 2025-11-11 13:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251111_add_description_to_leave_types'
down_revision = '20251111_104500_add_position_and_employment_status_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_types', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_types', 'description')
    # ### end Alembic commands ###