"""Add user_invitations table

Revision ID: 20251111_104000
Revises: 20251110_change_company_id_to_string
Create Date: 2025-11-11 10:40:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20251111_104000'
down_revision = '20251110_change_company_id_to_string'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table('user_invitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('accepted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_user_invitations_invitation_id'), 'user_invitations', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.create_foreign_key('fk_user_invitations_invited_by', 'user_invitations', 'users', ['invited_by'], ['user_id'])
    op.create_foreign_key('fk_user_invitations_role_id', 'user_invitations', 'roles', ['role_id'], ['role_id'])
    op.create_foreign_key('fk_user_invitations_department_id', 'user_invitations', 'departments', ['department_id'], ['department_id'])
    op.create_foreign_key('fk_user_invitations_employee_profile_id', 'user_invitations', 'employees', ['employee_profile_id'], ['employee_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.drop_constraint('fk_user_invitations_employee_profile_id', 'user_invitations', type_='foreignkey')
    op.drop_constraint('fk_user_invitations_department_id', 'user_invitations', type_='foreignkey')
    op.drop_constraint('fk_user_invitations_role_id', 'user_invitations', type_='foreignkey')
    op.drop_constraint('fk_user_invitations_invited_by', 'user_invitations', type_='foreignkey')
    op.drop_index(op.f('ix_user_invitations_token'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_invitation_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###