"""change_company_id_to_string

Revision ID: 20251110_change_company_id_to_string
Revises: 20250925_091600_add_office_and_employee_tables
Create Date: 2025-11-10 09:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251110_change_company_id_to_string'
down_revision = '20250925_091600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'company_id',
                    existing_type=sa.Integer(),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'company_id',
                    existing_type=sa.String(length=50),
                    type_=sa.Integer(),
                    existing_nullable=False)
    # ### end Alembic commands ###