"""Add Office and Employee tables

Revision ID: 20250925_091600
Revises: 20250909_update_payslip_model
Create Date: 2025-09-25 09:12:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250925_091600'
down_revision = '20250909_update_payslip_model'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table('offices',
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('office_id'),
    sa.UniqueConstraint('office_name')
    )
    # Add foreign key to users for office (optional, if needed)
    # op.add_column('users', sa.Column('office_id', sa.Integer(), nullable=True))
    # op.create_foreign_key('fk_users_office', 'users', 'offices', ['office_id'], ['office_id'])

    # Create Employee table (separate from User)
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('civil_status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('blood_type', sa.String(length=3), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('landline_number', sa.String(length=20), nullable=True),
    sa.Column('personal_email', sa.String(length=150), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('date_regularised', sa.Date(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('line_manager_id', sa.Integer(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(10, 2), nullable=True),
    sa.Column('pay_frequency', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_foreign_key('fk_employee_department', 'employees', 'departments', ['department_id'], ['department_id'])
    op.create_foreign_key('fk_employee_role', 'employees', 'roles', ['role_id'], ['role_id'])
    op.create_foreign_key('fk_employee_office', 'employees', 'offices', ['office_id'], ['office_id'])
    op.create_foreign_key('fk_employee_line_manager', 'employees', 'users', ['line_manager_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.drop_constraint('fk_employee_line_manager', 'employees', type_='foreignkey')
    op.drop_constraint('fk_employee_office', 'employees', type_='foreignkey')
    op.drop_constraint('fk_employee_role', 'employees', type_='foreignkey')
    op.drop_constraint('fk_employee_department', 'employees', type_='foreignkey')
    op.drop_table('employees')
    # op.drop_column('users', 'office_id')
    op.drop_table('offices')
    # ### end Alembic commands ###